spring:
  jpa:
    generate-ddl: 'false'
    database: oracle
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    database-platform: org.hibernate.dialect.Oracle10gDialect
  thymeleaf:
    cache: 'false'
    prefix: classpath:/templates/fragments/
  datasource:
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: c##planetime
    url: jdbc:oracle:thin:@localhost:1521:XE
  devtools:
    livereload:
      enabled: 'true'
  mail:
    host: smtp.naver.com  #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    username: ajtwlswldn789@naver.com #네이버 아이디
    password: gkgkghgh2548@ #네이버 비밀번호
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true #반드시 필요 -> SSL 필요로 되어있으면
logging:
  level:
    org:
      hibernate: info
server:
  port: '8081'


handlebars:
  suffix: .html
  expose-session-attributes: true
